[build]
builder = "nixpacks"
buildCommand = "cd ../.. && pnpm install && pnpm build:server"

[deploy]
startCommand = "cd apps/server && node dist/index.js"
healthcheckPath = "/"
healthcheckTimeout = 100

[service]
internal_port = 3000